{-# LANGUAGE OverloadedStrings #-}

module Intray.Web.Server.Handler.APIDocs
  ( getAPIDocsR,
  )
where

import Import
import Intray.API
import Intray.Client
import Intray.Web.Server.Foundation
import Yesod

getAPIDocsR :: Handler Html
getAPIDocsR = do
  GetDocsResponse html <- runClientOrErr clientGetDocs
  -- If we ever separate the API from the web server
  -- and this becomes a well-traveled route, then we may want
  -- to cache the API docs.
  defaultLayout $ do
    setTitle "API Docs"
    setDescription "Autogenerated API Documentation"
    toWidget html
